# name: Test

# on: [push]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     env:
#       MYSQL_HOST: "127.0.0.1"
#       MYSQL_PORT: "3306"
#       MYSQL_USER: "user1"
#       MYSQL_PASSWORD: "password1"
#       API_URL: "https://localhost:3000/healthz" # Replace with your API URL

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Setup Node.js
#       uses: actions/setup-node@v2
#       with:
#         node-version: 14

#     - name: Install dependencies
#       run: npm install

#     - name: Install MySQL Server
#       run: |
#         sudo apt-get update -y
#         sudo apt-get install -y mysql-server
#       env:
#         DEBIAN_FRONTEND: noninteractive
        
#     - name: Create Database and User
#       run: |
#         sudo mysql -e "CREATE DATABASE cloud_assignment_3;"
#         sudo mysql -e "CREATE USER 'user1'@'127.0.0.1' IDENTIFIED BY 'password1';"
#         sudo mysql -e "GRANT ALL PRIVILEGES ON mydatabase.* TO 'user1'@'127.0.0.1';"
#         sudo mysql -e "FLUSH PRIVILEGES;"
  
#     - name: Set up MySQL
#       run: |
#         sudo service mysql start
#         mysql -h $MYSQL_HOST -P $MYSQL_PORT -u $MYSQL_USER -p $MYSQL_PASSWORD -e "CREATE DATABASE IF NOT EXISTS cloud_assignment_3"

#     - name: Start Node.js application
#       run: npm start &

#     - name: Wait for application to start
#       run: sleep 10

#     - name: Test API status
#       run: |
#         response_code=$(curl -sL -w "%{http_code}" $API_URL -o /dev/null)
#         if [[ $response_code -eq 200 ]]; then
#           echo "API is up and running with a 200 OK status code."
#         else
#           echo "API is not responding with a 200 OK status code. Status code: $response_code"
#           exit 1
#         fi

name: test

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: testing
        run: echo "Hello World!"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Test cases
        run: npx jest

      - name: Building the Artifacts
        run: zip -r release.zip .
