
name: test

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: testing
        run: echo "Hello World!"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup MySql
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: ${{ secrets.MYSQL_DATABASE }}
          mysql root password: ${{ secrets.MYSQL_PASSWORD }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Setup envirornment variables
        run: |
          touch .env
          echo MYSQL_HOST=${{ secrets.MYSQL_HOST }} >> .env
          echo MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE}} >> .env
          echo MYSQL_USER=${{ secrets.MYSQL_USER }} >> .env
          echo MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} >> .env

      - name: Install dependencies
        run: npm install

      - name: Test cases
        run: npx jest

      - name: Building the Artifacts
        run: zip -r release.zip .
