# name: Build AMI with Packer

# on:
#   pull_request:
#     branches:
#       - main
#     types: [closed]

# jobs:
#   create-zip:
#     runs-on: ubuntu-latest
#     if: github.event.pull_request.merged == true
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v2
#       - name: Create Zip Archive
#         run: |
#           zip -r madhura_kurhadkar_002769373_06.zip ./

#       - name: Build AMI
#         run: |
#           packer init aws-debian.pkr.hcl
#           packer fmt -check aws-debian.pkr.hcl
#           packer validate aws-debian.pkr.hcl
#           packer build aws-debian.pkr.hcl
#         env:
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


name: Build AMI with Packer

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  create-zip:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Create Zip Archive
        run: |
          zip -r madhura_kurhadkar_002769373_06.zip ./

      - name: Build AMI
        run: |
          packer init aws-debian.pkr.hcl
          packer fmt -check aws-debian.pkr.hcl
          packer validate aws-debian.pkr.hcl
          packer build aws-debian.pkr.hcl
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Setup demo credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_DEMO}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY_DEMO}}
          aws-region: ${{secrets.AWS_REGION}}
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
      - name: Get latest ami id
        run: |
          LATEST_AMI_ID=$(aws ec2 describe-images --filters "Name=state,Values=available" --query 'sort_by(Images, &CreationDate)[-1].ImageId' --output text)
          echo "LATEST_AMI_ID=$LATEST_AMI_ID" >> $GITHUB_ENV
      - name: Get latest launch template id
        run: |
          LATEST_LT_ID=$(aws ec2 describe-launch-templates --query 'sort_by(LaunchTemplates, &CreateTime)[-1].LaunchTemplateId' --output text)
          echo "LATEST_LT_ID=$LATEST_LT_ID" >> $GITHUB_ENV
      - name: Get latest launch template version
        run: |
          LATEST_VERSION=$(aws ec2 describe-launch-templates --launch-template-ids $LATEST_LT_ID --query 'LaunchTemplates[0].LatestVersionNumber' --output text)
          echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV
      - run: |
          echo "{"ImageId":\"$LATEST_AMI_ID\"}"
          echo $LATEST_AMI_ID
      - name: Create a new version of the Launch Template
        run: aws ec2 create-launch-template-version --launch-template-id $LATEST_LT_ID --source-version $LATEST_VERSION --launch-template-data "{\"ImageId\":\"$LATEST_AMI_ID\"}"

      - name: Get Auto Scaling Group Name
        run: |
          ASG_NAME=$(aws autoscaling describe-auto-scaling-groups --query "AutoScalingGroups[0].AutoScalingGroupName" --output text)
          echo "ASG_NAME=$ASG_NAME" >> $GITHUB_ENV
      - name: Start instance fresh
        run: aws autoscaling start-instance-refresh --auto-scaling-group-name $ASG_NAME

      - name: Wait for Instance Refresh Completion
        id: wait-instance-refresh
        run: |
          while :
          do
            refresh_status=$(aws autoscaling describe-instance-refreshes --auto-scaling-group-name $ASG_NAME --query 'InstanceRefreshes[0].Status' --output text)
            if [ "$refresh_status" = "Successful" ]; then
              echo "Instance refresh completed successfully"
              break
            elif [ "$refresh_status" = "Failed" ]; then
              echo "Instance refresh failed"
              exit 1
            else
              echo "Instance refresh in progress..."
              sleep 30
            fi
          done
 
      - name: Workflow Status
        if: steps.wait-instance-refresh.outcome == 'failure'
        run: exit 1
