# name: Build AMI with Packer

# on:
#   pull_request:
#     branches:
#       - main
#     types: [closed]

# jobs:
#   create-zip:
#     runs-on: ubuntu-latest
#     if: github.event.pull_request.merged == true
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v2
#       - name: Create Zip Archive
#         run: |
#           zip -r madhura_kurhadkar_002769373_06.zip ./

#       - name: Build AMI
#         run: |
#           packer init aws-debian.pkr.hcl
#           packer fmt -check aws-debian.pkr.hcl
#           packer validate aws-debian.pkr.hcl
#           packer build aws-debian.pkr.hcl
#         env:
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


name: Build AMI with Packer

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  create-zip:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Create Zip Archive
        run: |
          zip -r madhura_kurhadkar_002769373_06.zip ./

      - name: Build AMI
        run: |
          packer init aws-debian.pkr.hcl
          packer fmt -check aws-debian.pkr.hcl
          packer validate aws-debian.pkr.hcl
          packer build aws-debian.pkr.hcl
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Get Latest AMI ID
        id: latest-ami
        run: |
          latest_ami_id=$(aws ec2 describe-images --region ${{ secrets.AWS_REGION }} --owners self --query 'Images | sort_by(@, &CreationDate) | [-1].ImageId' --output text)
          echo "::set-output name=ami_id::$latest_ami_id"


      - name: Create New Launch Template Version
        run: |
          # Replace with actual commands to create a new Launch Template version using ${{ steps.latest-ami.outputs.ami_id }}

      - name: Issue Instance Refresh Command
        run: |
          # Use the retrieved AMI ID in the instance refresh command
          aws autoscaling start-instance-refresh --auto-scaling-group-name <your-auto-scaling-group-name> --latest-launch-template
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_DEMO }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEMO }}

      - name: Wait for Instance Refresh Completion
        id: wait-instance-refresh
        run: |
          # Replace the script below with code that checks and waits for instance refresh completion using the auto-scaling-group-name

      - name: Workflow Status
        if: steps.wait-instance-refresh.outcome == 'failure'
        run: exit 1
