# name: Build AMI with Packer

# on:
#   pull_request:
#     branches:
#       - main
#     types: [closed]

# jobs:
#   create-zip:
#     runs-on: ubuntu-latest
#     if: github.event.pull_request.merged == true
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v2
#       - name: Create Zip Archive
#         run: |
#           zip -r madhura_kurhadkar_002769373_06.zip ./

#       - name: Build AMI
#         run: |
#           packer init aws-debian.pkr.hcl
#           packer fmt -check aws-debian.pkr.hcl
#           packer validate aws-debian.pkr.hcl
#           packer build aws-debian.pkr.hcl
#         env:
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


name: Build AMI with Packer

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  create-zip:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Create Zip Archive
        run: |
          zip -r madhura_kurhadkar_002769373_06.zip ./

      - name: Build AMI
        run: |
          packer init aws-debian.pkr.hcl
          packer fmt -check aws-debian.pkr.hcl
          packer validate aws-debian.pkr.hcl
          packer build aws-debian.pkr.hcl
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Get Latest AMI ID
        id: latest-ami
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} --profile myprofile
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile myprofile
          latest_ami_id=$(aws ec2 describe-images --region ${{ secrets.AWS_REGION }} --owners self --query 'Images | sort_by(@, &CreationDate) | [-1].ImageId' --output text --profile myprofile)
          echo "::set-output name=ami_id::$latest_ami_id"


      - name: Create New Launch Template Version
        run: |
          aws ec2 create-launch-template-version --launch-template-name webAppLaunchTemplate --source-version $latest_ami_id --image-id ${{ steps.latest-ami.outputs.ami_id }}

      - name: Issue Instance Refresh Command
        run: |
          aws autoscaling start-instance-refresh --auto-scaling-group-name webAppAutoScalingGroup --latest-launch-template
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_DEMO }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEMO }}

      - name: Wait for Instance Refresh Completion
        id: wait-instance-refresh
        run: |
          while :
          do
            refresh_status=$(aws autoscaling describe-instance-refreshes --auto-scaling-group-name webAppAutoScalingGroup --query 'InstanceRefreshes[0].Status' --output text)
            if [ "$refresh_status" = "Successful" ]; then
              echo "Instance refresh completed successfully"
              break
            elif [ "$refresh_status" = "Failed" ]; then
              echo "Instance refresh failed"
              exit 1
            else
              echo "Instance refresh in progress..."
              sleep 30
            fi
          done

      - name: Workflow Status
        if: steps.wait-instance-refresh.outcome == 'failure'
        run: exit 1
